"""
SIH26006 - Synthetic / prototype data generator.

WHY THIS EXISTS
----------------
No proprietary SAIL freight contracts, no live AIS feed, and no licensed
Baltic-Exchange-grade freight index are available for this hackathon
prototype. Rather than leave the application empty (or, worse, silently
invent numbers that look official), every figure this script produces is
generated here, deterministically, and tagged with a `data_status` field:

    ESTIMATED  - dimensions/limits sourced from public, general maritime
                 knowledge (vessel-class envelopes, port draft classes)
                 but not verified against an official port-authority /
                 classification-society document. Order-of-magnitude
                 correct, NOT contract-grade.
    SYNTHETIC  - has no real-world source at all; generated by a
                 structured random process (freight-rate history, market
                 indicators) so the ML pipeline has something realistic
                 to learn from.

Nothing in this file is presented to the user as REAL. The backend and
frontend both propagate `data_status` end-to-end so the UI can render a
"PROTOTYPE / ESTIMATED / SYNTHETIC" badge next to every figure that comes
from here. See data/DATA_DICTIONARY.md for the field-by-field breakdown.

Run:  python3 generate_data.py
Output: CSVs under data/synthetic/
"""
import csv
import json
import math
import random
from datetime import date, timedelta
from pathlib import Path

SEED = 42
random.seed(SEED)

OUT_DIR = Path(__file__).parent
OUT_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# 1. PORTS  (East Coast India) - dimensional limits are ESTIMATED
# ---------------------------------------------------------------------------
PORTS = [
    dict(code="INPAR", name="Paradip", state="Odisha", lat=20.2648, lon=86.6947,
         port_type="Bulk / Deep Water", draft_limit_m=18.1, loa_limit_m=300.0, beam_limit_m=50.0,
         congestion="MEDIUM", risk="MEDIUM",
         compatible_classes=["Handysize", "Supramax", "Panamax", "Capesize"],
         notes="Major deep-water bulk terminal on Odisha coast; capesize-capable outer channel."),
    dict(code="INVTZ", name="Visakhapatnam", state="Andhra Pradesh", lat=17.6868, lon=83.2185,
         port_type="Bulk / Multi-purpose", draft_limit_m=17.0, loa_limit_m=280.0, beam_limit_m=45.0,
         congestion="MEDIUM", risk="MEDIUM",
         compatible_classes=["Handysize", "Supramax", "Panamax"],
         notes="Natural harbour; inner-harbour draft materially shallower than outer anchorage."),
    dict(code="INGAN", name="Gangavaram", state="Andhra Pradesh", lat=17.6167, lon=83.2833,
         port_type="Bulk / Deep Water (Private)", draft_limit_m=18.5, loa_limit_m=310.0, beam_limit_m=50.0,
         congestion="LOW", risk="LOW",
         compatible_classes=["Handysize", "Supramax", "Panamax", "Capesize"],
         notes="Private deep-water port purpose-built for capesize dry-bulk."),
    dict(code="INGOP", name="Gopalpur", state="Odisha", lat=19.2648, lon=84.9200,
         port_type="Bulk (Shallow Draft)", draft_limit_m=14.5, loa_limit_m=230.0, beam_limit_m=32.0,
         congestion="LOW", risk="MEDIUM",
         compatible_classes=["Handysize", "Supramax"],
         notes="Shallow-draft merchant port; capesize/panamax not compatible."),
    dict(code="INDHM", name="Dhamra", state="Odisha", lat=20.7833, lon=86.9833,
         port_type="Bulk / Deep Water (Private)", draft_limit_m=18.0, loa_limit_m=300.0, beam_limit_m=50.0,
         congestion="LOW", risk="LOW",
         compatible_classes=["Handysize", "Supramax", "Panamax", "Capesize"],
         notes="Deep-water private port; among the few Indian east-coast berths taking capesize."),
    dict(code="INSAG", name="Sagar-Sandheads", state="West Bengal", lat=21.6500, lon=88.0500,
         port_type="Anchorage / Transshipment", draft_limit_m=12.5, loa_limit_m=225.0, beam_limit_m=32.2,
         congestion="HIGH", risk="HIGH",
         compatible_classes=["Handysize", "Supramax"],
         notes="Outer anchorage serving Kolkata dock system; larger parcels lightered here, drives congestion."),
    dict(code="INHAL", name="Haldia", state="West Bengal", lat=22.0333, lon=88.0833,
         port_type="Bulk / River Port", draft_limit_m=9.0, loa_limit_m=186.0, beam_limit_m=28.0,
         congestion="HIGH", risk="HIGH",
         compatible_classes=["Handysize"],
         notes="Tidal river port on the Hooghly; hard draft ceiling, handysize only."),
]

# ---------------------------------------------------------------------------
# 2. OVERSEAS ORIGINS  (representative bulk-cargo load ports)
# ---------------------------------------------------------------------------
ORIGINS = [
    dict(code="AUNTL", country="Australia", name="Newcastle", lat=-32.9283, lon=151.7817,
         cargoes=["Coal", "Iron Ore"]),
    dict(code="IDSMR", country="Indonesia", name="Samarinda / Taboneo Anchorage", lat=-0.5022, lon=117.1536,
         cargoes=["Coal"]),
    dict(code="MZNAC", country="Mozambique", name="Nacala", lat=-14.5624, lon=40.6817,
         cargoes=["Coal"]),
    dict(code="RUVVO", country="Russia", name="Vostochny", lat=42.7500, lon=133.0833,
         cargoes=["Coal"]),
    dict(code="USNFK", country="United States", name="Norfolk", lat=36.8508, lon=-76.2859,
         cargoes=["Coal"]),
]

# ---------------------------------------------------------------------------
# 3. VESSEL CLASSES - dimensional envelopes are ESTIMATED (industry-typical)
# ---------------------------------------------------------------------------
VESSEL_CLASSES = [
    dict(code="HANDY", name="Handysize", dwt_tonnes=35000, draft_m=10.5, loa_m=190.0, beam_m=32.0,
         cargo_capacity_tonnes=34000, typical_daily_hire_usd=9500),
    dict(code="SUPRA", name="Supramax", dwt_tonnes=58000, draft_m=12.6, loa_m=190.0, beam_m=32.3,
         cargo_capacity_tonnes=56000, typical_daily_hire_usd=12800),
    dict(code="PANMX", name="Panamax", dwt_tonnes=82000, draft_m=14.5, loa_m=225.0, beam_m=32.2,
         cargo_capacity_tonnes=79000, typical_daily_hire_usd=15600),
    dict(code="CAPE", name="Capesize", dwt_tonnes=180000, draft_m=18.0, loa_m=300.0, beam_m=45.0,
         cargo_capacity_tonnes=175000, typical_daily_hire_usd=22500),
]


def haversine_nm(lat1, lon1, lat2, lon2):
    R_km = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlmb = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dlmb / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    km = R_km * c
    return round(km * 0.539957, 1)  # km -> nautical miles


# ---------------------------------------------------------------------------
# 4. FREIGHT RATE TIME SERIES (SYNTHETIC) - one lane per (origin, cargo)
# ---------------------------------------------------------------------------
LANES = []
for o in ORIGINS:
    for cargo in o["cargoes"]:
        LANES.append((o["code"], cargo))

WEEKS = 208  # 4 years of weekly history
START_DATE = date.today() - timedelta(weeks=WEEKS)

# Base level ($/tonne) and volatility per lane - synthetic but internally
# consistent (longer haul -> higher base rate; coal vs iron ore differ).
LANE_BASE = {
    ("AUNTL", "Coal"): 16.5,
    ("AUNTL", "Iron Ore"): 11.0,
    ("IDSMR", "Coal"): 9.5,
    ("MZNAC", "Coal"): 19.0,
    ("RUVVO", "Coal"): 24.0,
    ("USNFK", "Coal"): 27.0,
}
LANE_VOL = {  # weekly noise std as fraction of base
    ("AUNTL", "Coal"): 0.035,
    ("AUNTL", "Iron Ore"): 0.045,
    ("IDSMR", "Coal"): 0.03,
    ("MZNAC", "Coal"): 0.05,
    ("RUVVO", "Coal"): 0.06,
    ("USNFK", "Coal"): 0.05,
}

market_rows = []  # exogenous market indicator: synthetic bunker price index
bunker_level = 480.0  # USD/tonne VLSFO, synthetic starting point
bunker_series = []
for w in range(WEEKS + 26):  # extra 26 weeks so forecast horizon has "future" context internally
    d = START_DATE + timedelta(weeks=w)
    cyc = 25 * math.sin(2 * math.pi * w / 52.0)
    shock = random.gauss(0, 6)
    bunker_level = max(280.0, bunker_level * 0.995 + 0.005 * (520 + cyc) + shock * 0.15)
    bunker_series.append(bunker_level)
    market_rows.append(dict(date=d.isoformat(), indicator="bunker_price_vlsfo_usd_per_tonne",
                             value=round(bunker_level, 2), data_status="SYNTHETIC"))

freight_rows = []
lane_ar_state = {lane: 0.0 for lane in LANES}
for lane in LANES:
    base = LANE_BASE[lane]
    vol = LANE_VOL[lane]
    # random long-horizon drift: some lanes trend down, some up, some flat
    drift_choice = random.choice([-1, -1, 0, 1])
    annual_drift_pct = drift_choice * random.uniform(0.03, 0.09)
    ar_phi = 0.82  # mean-reverting AR(1) noise
    level = base
    state = 0.0
    for w in range(WEEKS):
        d = START_DATE + timedelta(weeks=w)
        # seasonality: Q4/Q1 (northern winter) modestly higher demand for thermal coal
        month = d.month
        seasonal = 0.06 * math.sin(2 * math.pi * (month - 1) / 12.0 + math.pi / 3)
        trend = base * (annual_drift_pct * (w / 52.0))
        # occasional congestion/geopolitical shock (sparse)
        shock = 0.0
        if random.random() < 0.015:
            shock = random.choice([-1, 1]) * base * random.uniform(0.08, 0.20)
        state = ar_phi * state + random.gauss(0, vol * base)
        bunker_component = (bunker_series[w] - 480.0) * 0.01  # small pass-through
        rate = max(2.0, base + trend + seasonal * base + state + shock + bunker_component)
        freight_rows.append(dict(
            date=d.isoformat(),
            origin_code=lane[0],
            cargo_type=lane[1],
            rate_usd_per_tonne=round(rate, 3),
            data_status="SYNTHETIC",
        ))
        level = rate

# ---------------------------------------------------------------------------
# 5. ROUTES (origin -> destination port), derived from lanes + real geometry
# ---------------------------------------------------------------------------
route_rows = []
latest_rate_by_lane = {}
for lane in LANES:
    rows = [r for r in freight_rows if r["origin_code"] == lane[0] and r["cargo_type"] == lane[1]]
    rows.sort(key=lambda r: r["date"])
    latest_rate_by_lane[lane] = rows[-1]["rate_usd_per_tonne"]
    prev_rate = rows[-9]["rate_usd_per_tonne"] if len(rows) > 9 else rows[0]["rate_usd_per_tonne"]
    lane_trend_pct = (rows[-1]["rate_usd_per_tonne"] - prev_rate) / prev_rate

# Indicative ANNUAL trade volume per origin-cargo lane (SYNTHETIC, in million
# tonnes/year). Order-of-magnitude only, loosely informed by the well-known
# relative scale of these countries' seaborne coal/iron-ore exports (e.g.
# Australia and Indonesia are the world's largest thermal-coal exporters) -
# NOT sourced from any customs/trade dataset. Drives route line-width on the
# Global Network map so width always traces back to a disclosed number
# rather than being a decorative random value.
LANE_ANNUAL_VOLUME_MT = {
    ("AUNTL", "Coal"): 38.0,
    ("AUNTL", "Iron Ore"): 22.0,
    ("IDSMR", "Coal"): 30.0,
    ("MZNAC", "Coal"): 9.0,
    ("RUVVO", "Coal"): 14.0,
    ("USNFK", "Coal"): 11.0,
}
# Port capacity weight: deep-water Capesize-capable ports can realistically
# absorb a larger share of a lane's volume than shallow-draft ports.
PORT_CAPACITY_WEIGHT = {
    "INPAR": 1.6, "INGAN": 1.5, "INDHM": 1.5,  # deep water, capesize-capable
    "INVTZ": 1.1, "INGOP": 0.6, "INSAG": 0.5, "INHAL": 0.4,  # shallower / constrained
}

origin_by_code = {o["code"]: o for o in ORIGINS}
route_id = 1
for o in ORIGINS:
    for cargo in o["cargoes"]:
        lane = (o["code"], cargo)
        base_rate = latest_rate_by_lane[lane]
        rows = [r for r in freight_rows if r["origin_code"] == lane[0] and r["cargo_type"] == lane[1]]
        rows.sort(key=lambda r: r["date"])
        prev_rate = rows[-9]["rate_usd_per_tonne"]
        pct = (rows[-1]["rate_usd_per_tonne"] - prev_rate) / prev_rate
        trend = "increasing" if pct > 0.015 else ("decreasing" if pct < -0.015 else "stable")

        # distribute the lane's indicative annual volume across the 7 destination
        # ports, weighted by port capacity and inversely by distance (closer/
        # deeper ports absorb a larger realistic share).
        raw_weights = {}
        for p in PORTS:
            d = haversine_nm(o["lat"], o["lon"], p["lat"], p["lon"])
            raw_weights[p["code"]] = PORT_CAPACITY_WEIGHT.get(p["code"], 1.0) * (1.0 / max(d, 1.0))
        weight_sum = sum(raw_weights.values())
        lane_total_mt = LANE_ANNUAL_VOLUME_MT.get((o["code"], cargo), 10.0)

        for p in PORTS:
            dist_nm = haversine_nm(o["lat"], o["lon"], p["lat"], p["lon"])
            # small port-specific premium: longer inland/lighterage handling -> higher $/t
            port_premium = {"LOW": 0.0, "MEDIUM": 0.015, "HIGH": 0.04}[p["congestion"]]
            reference_freight = round(base_rate * (1 + port_premium + dist_nm / 250000.0), 3)
            volume_share = raw_weights[p["code"]] / weight_sum
            indicative_annual_volume_tonnes = round(lane_total_mt * 1_000_000 * volume_share)
            route_rows.append(dict(
                route_id=f"R{route_id:03d}",
                origin_code=o["code"],
                origin_country=o["country"],
                origin_name=o["name"],
                destination_code=p["code"],
                destination_name=p["name"],
                cargo_type=cargo,
                distance_nm=dist_nm,
                reference_freight_usd_per_tonne=reference_freight,
                indicative_annual_volume_tonnes=indicative_annual_volume_tonnes,
                trend=trend,
                trend_pct_8wk=round(pct * 100, 2),
                congestion=p["congestion"],
                risk=p["risk"],
                route_status="active",
                data_status="SYNTHETIC",
            ))
            route_id += 1

# ---------------------------------------------------------------------------
# WRITE CSVs
# ---------------------------------------------------------------------------
def write_csv(name, rows):
    if not rows:
        return
    path = OUT_DIR / name
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        for r in rows:
            writer.writerow({k: (json.dumps(v) if isinstance(v, list) else v) for k, v in r.items()})
    print(f"wrote {len(rows):>6} rows -> {path}")


write_csv("ports.csv", [{**p, "compatible_classes": p["compatible_classes"]} for p in PORTS])
write_csv("origins.csv", [{**o, "cargoes": o["cargoes"]} for o in ORIGINS])
write_csv("vessel_classes.csv", VESSEL_CLASSES)
write_csv("routes.csv", route_rows)
write_csv("freight_rate_history.csv", freight_rows)
write_csv("market_indicators.csv", market_rows)

print("\nSynthetic data generation complete.")
print(f"Lanes: {len(LANES)} | Routes: {len(route_rows)} | Freight history rows: {len(freight_rows)}")
